"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { LogOut, ExternalLink, RefreshCw, Inbox, Mail } from "lucide-react";
import { cn } from "@/lib/utils";
import type { AnalysisResult } from "@/lib/types";

interface CandidateRow {
  github_username: string;
  larp_score: number | null;
  analyzed_at: string;
}

interface InboxThread {
  threadId: string;
  fromEmail: string;
  fromName: string;
  subject: string;
  snippet: string;
  date: string;
  githubUsername: string | null;
  reportScore: number | null;
  reportSubject: string | null;
  reportText: string | null;
  hasReport: boolean;
}

function scoreColor(n: number | null) {
  if (n === null) return "#64748b";
  if (n >= 70) return "#ef4444";
  if (n >= 40) return "#f97316";
  return "#4ade80";
}

function verdictFromScore(n: number | null): "CONTRADICTED" | "UNVERIFIED" | "SUPPORTED" | "PENDING" {
  if (n === null) return "PENDING";
  if (n >= 70) return "CONTRADICTED";
  if (n >= 40) return "UNVERIFIED";
  return "SUPPORTED";
}

const verdictStyle: Record<string, string> = {
  CONTRADICTED: "bg-red-500/10 text-red-200 border border-red-400/20",
  UNVERIFIED: "bg-amber-500/10 text-amber-200 border border-amber-400/20",
  SUPPORTED: "bg-emerald-500/10 text-emerald-200 border border-emerald-400/20",
  PENDING: "bg-slate-700/40 text-slate-300 border border-slate-600/50",
};

const REPORT_HEADINGS = [
  "Receipts",
  "Indexed by Nia",
  "Recent Activity",
  "What to Ask Next",
  "Generated by LARPbot",
];

function formatDate(iso: string) {
  if (!iso) return "—";
  try {
    return new Date(iso).toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  } catch {
    return iso.slice(0, 10);
  }
}

function Initials({ name }: { name: string }) {
  const letters = name.replace(/[^a-zA-Z]/g, "").slice(0, 2).toUpperCase() || "??";
  return (
    <div className="w-8 h-8 rounded-full bg-slate-700 flex items-center justify-center text-xs font-bold text-slate-300 flex-shrink-0">
      {letters}
    </div>
  );
}

function cleanReportText(text: string): string {
  return text
    .replace(/Automated candidate verification/g, "")
    .replace(/Generated by LARPbot\s*·?.*/gi, "")
    .replace(/\s+·\s+/g, " · ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function splitReportSections(text: string) {
  const cleaned = cleanReportText(text);
  const lines = cleaned.split(/\n+/).map((line) => line.trim()).filter(Boolean);
  const intro: string[] = [];
  const sections: Array<{ title: string; lines: string[] }> = [];
  let current: { title: string; lines: string[] } | null = null;

  for (const line of lines) {
    const heading = REPORT_HEADINGS.find((h) => line.toLowerCase().startsWith(h.toLowerCase()));
    if (heading) {
      current = { title: heading, lines: [] };
      sections.push(current);
      const rest = line.slice(heading.length).trim();
      if (rest) current.lines.push(rest);
      continue;
    }
    if (current) current.lines.push(line);
    else intro.push(line);
  }

  return { intro, sections };
}

function reportVerdictLine(lines: string[]) {
  return lines.find((line) => {
    const lower = line.toLowerCase();
    return !lower.includes("larp report:") && !lower.includes("larp score") && line.length > 20;
  });
}

interface MergedRow {
  username: string;
  fromEmail: string | null;
  fromName: string | null;
  subject: string | null;
  larpScore: number | null;
  threadId: string | null;
  date: string;
  hasReport: boolean;
  reportInEmail: boolean;
  reportSubject: string | null;
  reportText: string | null;
}

function mergeData(candidates: CandidateRow[], threads: InboxThread[]): MergedRow[] {
  const byUser = new Map<string, MergedRow>();

  for (const c of candidates) {
    byUser.set(c.github_username.toLowerCase(), {
      username: c.github_username,
      fromEmail: null,
      fromName: null,
      subject: null,
      larpScore: c.larp_score,
      threadId: null,
      date: c.analyzed_at,
      hasReport: true,
      reportInEmail: false,
      reportSubject: null,
      reportText: null,
    });
  }

  for (const t of threads) {
    const u = (t.githubUsername || "").toLowerCase();
    const existing = u ? byUser.get(u) : undefined;
    if (existing) {
      existing.fromEmail = t.fromEmail;
      existing.fromName = t.fromName;
      existing.subject = t.subject;
      existing.threadId = t.threadId;
      existing.hasReport = existing.hasReport || t.hasReport;
      existing.reportInEmail = existing.reportInEmail || t.hasReport;
      existing.reportSubject = existing.reportSubject || t.reportSubject;
      existing.reportText = existing.reportText || t.reportText;
      if (existing.larpScore === null && t.reportScore !== null) existing.larpScore = t.reportScore;
      if (!existing.date) existing.date = t.date;
    } else {
      // Pending — emailed in but no LARP report yet
      const key = u || `__thread_${t.threadId}`;
      byUser.set(key, {
        username: t.githubUsername || "(no github)",
        fromEmail: t.fromEmail,
        fromName: t.fromName,
        subject: t.subject,
        larpScore: t.reportScore,
        threadId: t.threadId,
        date: t.date,
        hasReport: t.hasReport,
        reportInEmail: t.hasReport,
        reportSubject: t.reportSubject,
        reportText: t.reportText,
      });
    }
  }

  return Array.from(byUser.values()).sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
  );
}

export default function Dashboard() {
  const [candidates, setCandidates] = useState<CandidateRow[]>([]);
  const [threads, setThreads] = useState<InboxThread[]>([]);
  const [inbox, setInbox] = useState<string>("tungtungrecruiting@gmail.com");
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [companyValues, setCompanyValues] = useState(
    "Customer obsession, ownership, high judgment, bias for shipping, low-ego collaboration, and engineering quality that survives production."
  );
  const [roleSignals, setRoleSignals] = useState(
    "Senior Software Engineer: knowledge of backend systems, API design, databases, distributed systems, observability, production debugging, Rust experience, code review maturity, and evidence of owning projects beyond prototypes."
  );
  const [selected, setSelected] = useState<{
    row: MergedRow;
    result: AnalysisResult | null;
    reportError?: string | null;
  } | null>(null);

  async function load() {
    setRefreshing(true);
    setError(null);
    try {
      const [cRes, iRes] = await Promise.all([
        fetch("/api/candidates"),
        fetch("/api/inbox"),
      ]);
      if (cRes.ok) {
        const data = await cRes.json();
        setCandidates(Array.isArray(data) ? data : []);
      }
      if (iRes.ok) {
        const data = await iRes.json();
        setThreads(data.threads || []);
        if (data.inbox) setInbox(data.inbox);
      } else {
        const data = await iRes.json().catch(() => ({}));
        setError(data.error || "Failed to load inbox");
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to load");
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }

  useEffect(() => {
    void Promise.resolve().then(load);
  }, []);

  async function openCandidate(row: MergedRow) {
    setSelected({ row, result: null });
    if (!row.hasReport || row.username === "(no github)") {
      setSelected({
        row,
        result: null,
        reportError: row.reportText ? null : "No structured report is available yet.",
      });
      return;
    }
    try {
      const res = await fetch("/api/candidates", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ githubUsername: row.username }),
      });
      if (res.ok) {
        const data = await res.json();
        setSelected({ row, result: data });
      } else {
        const data = await res.json().catch(() => ({}));
        setSelected({
          row,
          result: null,
          reportError: row.reportText
            ? null
            : data.error || "Structured report was not found in agent memory.",
        });
      }
    } catch {
      setSelected({
        row,
        result: null,
        reportError: row.reportText ? null : "Could not load the structured report from agent memory.",
      });
    }
  }

  const rows = mergeData(candidates, threads);
  const stats = {
    total: rows.length,
    withReport: rows.filter((r) => r.hasReport).length,
    pending: rows.filter((r) => !r.hasReport && r.username !== "(no github)").length,
    avgScore:
      rows.filter((r) => r.larpScore !== null).reduce((s, r) => s + (r.larpScore || 0), 0) /
        Math.max(1, rows.filter((r) => r.larpScore !== null).length) || 0,
  };

  return (
    <div className="h-screen overflow-hidden bg-[#0b1120] text-white font-sans flex flex-col">
      {/* Nav */}
      <nav className="flex-shrink-0 flex items-center justify-between px-8 py-4 border-b border-white/10 bg-[#0b1120]/90 backdrop-blur">
        <Link href="/" className="text-lg font-semibold tracking-tight">
          <span className="text-sky-300">LARP</span>
          <span className="text-white">bot</span>
        </Link>
        <div className="flex items-center gap-4">
          <span className="text-xs text-slate-500 flex items-center gap-1.5">
            <Inbox size={12} /> {inbox}
          </span>
          <button
            onClick={load}
            disabled={refreshing}
            className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-white transition-colors disabled:text-slate-600"
          >
            <RefreshCw size={12} className={refreshing ? "animate-spin" : ""} />
            Refresh
          </button>
          <Link
            href="/"
            className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-white transition-colors"
          >
            <LogOut size={13} />
            Sign out
          </Link>
        </div>
      </nav>

      {/* Body */}
      <div className="flex-1 overflow-y-auto px-8 py-6 bg-[radial-gradient(circle_at_top_right,rgba(14,165,233,0.12),transparent_34%),radial-gradient(circle_at_top_left,rgba(16,185,129,0.08),transparent_30%)]">
        <div className="max-w-6xl mx-auto flex flex-col gap-6">
          <div className="flex items-end justify-between">
            <div>
              <h1 className="text-2xl font-semibold text-white tracking-tight">
                Dashboard
              </h1>
              <p className="text-sm text-slate-500 mt-0.5">
                Applicants who emailed{" "}
                <span className="text-slate-400">{inbox}</span>
              </p>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-[1.1fr_0.9fr] gap-3">
            <div className="bg-white/[0.04] border border-white/10 rounded-xl p-4 shadow-2xl shadow-black/10">
              <label className="block text-[0.65rem] uppercase tracking-widest text-slate-500 font-semibold mb-2">
                Company values
              </label>
              <textarea
                value={companyValues}
                onChange={(e) => setCompanyValues(e.target.value)}
                className="w-full min-h-24 resize-none bg-slate-950/50 border border-white/10 rounded-lg px-3 py-2 text-sm text-slate-200 placeholder:text-slate-600 focus:outline-none focus:border-sky-400"
              />
            </div>
            <div className="bg-white/[0.04] border border-white/10 rounded-xl p-4 shadow-2xl shadow-black/10">
              <label className="block text-[0.65rem] uppercase tracking-widest text-slate-500 font-semibold mb-2">
                Role calibration
              </label>
              <textarea
                value={roleSignals}
                onChange={(e) => setRoleSignals(e.target.value)}
                className="w-full min-h-24 resize-none bg-slate-950/50 border border-white/10 rounded-lg px-3 py-2 text-sm text-slate-200 placeholder:text-slate-600 focus:outline-none focus:border-sky-400"
              />
            </div>
          </div>

          <div className="bg-sky-400/[0.06] border border-sky-300/20 rounded-xl px-5 py-4">
            <div className="text-[0.65rem] uppercase tracking-widest text-sky-300 font-semibold mb-2">
              Senior Software Engineer
            </div>
            <p className="text-sm text-slate-300">
              Knowledge of backend architecture, durable APIs, data modeling,
              production ownership, system design tradeoffs, observability, and
              hands-on Rust experience. LARPbot compares each report against
              these fake demo priorities so judges can see the recruiting use case.
            </p>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-4 gap-3">
            <Stat label="Threads" value={stats.total} />
            <Stat label="With Report" value={stats.withReport} />
            <Stat label="Pending" value={stats.pending} />
            <Stat
              label="Avg LARP"
              value={Math.round(stats.avgScore)}
              colored
            />
          </div>

          {error && (
            <div className="bg-red-950/40 border border-red-900 rounded p-3 text-sm text-red-300">
              {error}
            </div>
          )}

          {/* Table */}
          <div className="bg-white/[0.04] border border-white/10 rounded-xl overflow-hidden shadow-2xl shadow-black/20">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-slate-700/60 text-[0.65rem] uppercase tracking-widest text-slate-500">
                  <th className="text-left px-5 py-3 font-semibold">Applicant</th>
                  <th className="text-left px-5 py-3 font-semibold">GitHub</th>
                  <th className="text-left px-5 py-3 font-semibold">Email subject</th>
                  <th className="text-left px-5 py-3 font-semibold">Verdict</th>
                  <th className="text-left px-5 py-3 font-semibold">LARP score</th>
                  <th className="text-left px-5 py-3 font-semibold">Date</th>
                  <th className="px-5 py-3" />
                </tr>
              </thead>
              <tbody>
                {loading && (
                  <tr>
                    <td colSpan={7} className="px-5 py-12 text-center text-slate-500 text-sm">
                      Loading…
                    </td>
                  </tr>
                )}
                {!loading && rows.length === 0 && (
                  <tr>
                    <td colSpan={7} className="px-5 py-12 text-center text-slate-500 text-sm">
                      No applicants yet. Recruiters email{" "}
                      <span className="text-slate-400">{inbox}</span> with a
                      github.com/&lt;user&gt; URL to get started.
                    </td>
                  </tr>
                )}
                {rows.map((r, i) => {
                  const verdict = verdictFromScore(r.larpScore);
                  return (
                    <tr
                      key={r.threadId || r.username || i}
                      className={cn(
                        "border-b border-slate-700/40 hover:bg-slate-700/20 transition-colors cursor-pointer",
                        i === rows.length - 1 && "border-b-0"
                      )}
                      onClick={() => openCandidate(r)}
                    >
                      <td className="px-5 py-3.5">
                        <div className="flex items-center gap-2.5">
                          <Initials name={r.fromName || r.username} />
                          <div>
                            <div className="font-semibold text-slate-200">
                              {r.fromName || r.username}
                            </div>
                            <div className="text-[0.7rem] text-slate-500 flex items-center gap-1">
                              <Mail size={9} /> {r.fromEmail || "—"}
                            </div>
                          </div>
                        </div>
                      </td>
                      <td className="px-5 py-3.5">
                        {r.username !== "(no github)" ? (
                          <a
                            href={`https://github.com/${r.username}`}
                            target="_blank"
                            rel="noopener noreferrer"
                            onClick={(e) => e.stopPropagation()}
                            className="text-xs text-slate-400 hover:text-sky-400"
                          >
                            {r.username}
                          </a>
                        ) : (
                          <span className="text-xs text-slate-600">none</span>
                        )}
                      </td>
                      <td className="px-5 py-3.5 text-slate-400 text-xs truncate max-w-[200px]">
                        {r.subject || "—"}
                      </td>
                      <td className="px-5 py-3.5">
                        <span
                          className={cn(
                            "px-2 py-0.5 rounded text-[0.65rem] font-bold uppercase tracking-wider",
                            verdictStyle[verdict]
                          )}
                        >
                          {verdict}
                        </span>
                      </td>
                      <td className="px-5 py-3.5">
                        {r.larpScore !== null ? (
                          <div className="flex items-center gap-2">
                            <div className="w-16 h-1.5 bg-slate-700 rounded overflow-hidden">
                              <div
                                className="h-full rounded"
                                style={{
                                  width: `${r.larpScore}%`,
                                  background: scoreColor(r.larpScore),
                                }}
                              />
                            </div>
                            <span
                              className="font-bold tabular-nums text-xs"
                              style={{ color: scoreColor(r.larpScore) }}
                            >
                              {r.larpScore}
                            </span>
                          </div>
                        ) : (
                          <span className="text-xs text-slate-600">—</span>
                        )}
                      </td>
                      <td className="px-5 py-3.5 text-slate-500 text-xs">
                        {formatDate(r.date)}
                      </td>
                      <td className="px-5 py-3.5">
                        <span className="flex items-center gap-1 text-xs text-slate-400">
                          {r.hasReport ? "View" : "Open"} <ExternalLink size={11} />
                        </span>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Drawer */}
      {selected && (
        <ReportDrawer
          row={selected.row}
          result={selected.result}
          reportError={selected.reportError}
          onClose={() => setSelected(null)}
        />
      )}
    </div>
  );
}

function Stat({ label, value, colored }: { label: string; value: number; colored?: boolean }) {
  return (
    <div className="bg-white/[0.04] border border-white/10 rounded-xl px-5 py-4 shadow-2xl shadow-black/10">
      <div className="text-[0.65rem] uppercase tracking-widest text-slate-500 font-semibold mb-1">
        {label}
      </div>
      <div
        className="text-3xl font-semibold tabular-nums"
        style={colored ? { color: scoreColor(value) } : undefined}
      >
        {value}
      </div>
    </div>
  );
}

function ReportDrawer({
  row,
  result,
  reportError,
  onClose,
}: {
  row: MergedRow;
  result: AnalysisResult | null;
  reportError?: string | null;
  onClose: () => void;
}) {
  return (
    <div
      className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex justify-end"
      onClick={onClose}
    >
      <div
        className="w-full max-w-3xl h-full bg-[#0b1120] border-l border-white/10 overflow-y-auto p-6 shadow-2xl shadow-black"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-start justify-between mb-4">
          <div>
            <h2 className="text-xl font-bold text-white">
              {row.fromName || row.username}
            </h2>
            <p className="text-xs text-slate-500 mt-0.5">{row.fromEmail}</p>
          </div>
          <button
            onClick={onClose}
            className="text-slate-500 hover:text-white text-2xl leading-none"
          >
            ×
          </button>
        </div>

        {!row.hasReport && (
          <div className="bg-slate-800 border border-slate-700 rounded p-4 text-sm text-slate-400">
            No LARP Report yet — applicant emailed in but the agent hasn&apos;t finished
            processing (or the email had no GitHub URL).
          </div>
        )}

        {row.hasReport && !result && !reportError && !row.reportText && (
          <div className="text-sm text-slate-500">Loading report…</div>
        )}

        {row.hasReport && !result && row.reportText && (
          <EmailReportFallback row={row} />
        )}

        {row.hasReport && !result && reportError && !row.reportText && (
          <div className="bg-slate-800 border border-amber-900/70 rounded p-4 text-sm text-slate-300 space-y-2">
            <p className="font-semibold text-amber-300">Report email found</p>
            <p className="text-slate-400">
              LARPbot replied in Gmail, but the structured dashboard report was
              not available from Tensorlake memory.
            </p>
            <div className="text-xs text-slate-500">
              {row.username !== "(no github)" && <p>GitHub: {row.username}</p>}
              {row.larpScore !== null && <p>LARP score from email: {row.larpScore}/100</p>}
              <p>{reportError}</p>
            </div>
          </div>
        )}

        {result && <InlineReport result={result} />}
      </div>
    </div>
  );
}

function EmailReportFallback({ row }: { row: MergedRow }) {
  const report = splitReportSections(row.reportText || "");
  const verdict = reportVerdictLine(report.intro);
  const intro = report.intro.filter((line) => {
    const lower = line.toLowerCase();
    return (
      line !== verdict &&
      !lower.includes("larp report:") &&
      !lower.includes("larp score") &&
      !lower.startsWith(row.username.toLowerCase())
    );
  });

  return (
    <div className="space-y-5">
      <div className="bg-white/[0.05] border border-white/10 rounded-xl p-5 shadow-2xl shadow-black/10">
        <div className="flex items-center justify-between gap-4">
          <div>
            <p className="text-xs uppercase tracking-widest text-slate-500">LARP Report</p>
            <h3 className="text-lg font-semibold text-white mt-1">
              {row.username !== "(no github)" ? row.username : row.fromName}
            </h3>
          </div>
          {row.larpScore !== null ? (
            <span className="text-4xl font-semibold tabular-nums" style={{ color: scoreColor(row.larpScore) }}>
              {row.larpScore}
              <span className="text-base text-slate-500">/100</span>
            </span>
          ) : (
            <span className="text-sm text-slate-500">from email</span>
          )}
        </div>
        {verdict && (
          <p className="text-sm text-slate-300 mt-4 leading-6">
            {verdict.replace(/^["“]|["”]$/g, "")}
          </p>
        )}
        {intro.length > 0 && (
          <div className="mt-4 grid gap-2">
            {intro.slice(0, 4).map((line, i) => (
              <p key={i} className="text-xs text-slate-500 leading-5">
                {line}
              </p>
            ))}
          </div>
        )}
      </div>

      <div className="grid gap-4">
        {report.sections.filter((section) => section.lines.length > 0).map((section) => (
          <ReportSectionCard key={section.title} title={section.title} lines={section.lines} />
        ))}
      </div>

      {report.sections.length === 0 && (
        <div className="bg-white/[0.04] border border-white/10 rounded-xl p-4">
          <p className="text-sm text-slate-300 leading-6 whitespace-pre-wrap">
            {cleanReportText(row.reportText || "")}
          </p>
        </div>
      )}
    </div>
  );
}

function ReportSectionCard({ title, lines }: { title: string; lines: string[] }) {
  const isReceipts = title === "Receipts";
  const isQuestions = title === "What to Ask Next";

  return (
    <section className="bg-white/[0.04] border border-white/10 rounded-xl p-4">
      <div className="flex items-center justify-between gap-3 mb-3">
        <h3 className="text-sm font-semibold text-slate-100">{title}</h3>
        {title === "Indexed by Nia" && (
          <span className="text-[0.65rem] uppercase tracking-widest text-indigo-200 bg-indigo-400/10 border border-indigo-300/20 rounded-full px-2 py-1">
            Nia context
          </span>
        )}
      </div>
      <div className="space-y-2">
        {lines.map((line, i) => {
          const cleaned = line.replace(/^[-•·✓]\s*/, "").trim();
          const urlMatch = cleaned.match(/https:\/\/github\.com\/\S+/);
          const url = urlMatch?.[0];
          return (
            <div
              key={`${title}-${i}`}
              className={cn(
                "rounded-lg border px-3 py-2 text-sm leading-6",
                isReceipts
                  ? "bg-slate-950/40 border-slate-700/60 text-slate-300"
                  : isQuestions
                  ? "bg-sky-400/[0.06] border-sky-300/20 text-sky-100"
                  : "bg-slate-950/25 border-white/10 text-slate-300"
              )}
            >
              {url ? (
                <a href={url} target="_blank" rel="noopener noreferrer" className="text-sky-300 hover:text-sky-200">
                  {cleaned}
                </a>
              ) : (
                cleaned
              )}
            </div>
          );
        })}
      </div>
    </section>
  );
}

function InlineReport({ result }: { result: AnalysisResult }) {
  const score = result.overallLarpScore;
  const color = scoreColor(score);
  return (
    <div className="space-y-5">
      <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-5">
        <div className="flex items-center justify-between">
          <span className="text-xs uppercase tracking-widest text-slate-500">LARP Score</span>
          <span className="text-3xl font-black tabular-nums" style={{ color }}>
            {score}
            <span className="text-base text-slate-600">/100</span>
          </span>
        </div>
        <p className="text-sm text-slate-300 italic mt-3">&ldquo;{result.overallVerdict}&rdquo;</p>
      </div>

      {result.niaIndexedRepos && result.niaIndexedRepos.length > 0 && (
        <div className="bg-slate-800/40 border border-indigo-900/40 rounded-xl p-4">
          <p className="text-[0.65rem] uppercase tracking-widest text-indigo-300 mb-2">
            Indexed by Nia ({result.niaQueriedRepos?.length ?? 0} of {result.niaIndexedRepos.length} queried)
          </p>
          <ul className="space-y-1">
            {result.niaIndexedRepos.map((slug) => {
              const queried = result.niaQueriedRepos?.includes(slug);
              return (
                <li key={slug} className="flex items-center gap-2 text-xs">
                  <span className={queried ? "text-indigo-400" : "text-slate-600"}>
                    {queried ? "✓" : "·"}
                  </span>
                  <a
                    href={`https://github.com/${slug}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className={queried ? "text-indigo-300" : "text-slate-500"}
                  >
                    {slug}
                  </a>
                </li>
              );
            })}
          </ul>
        </div>
      )}

      <div>
        <p className="text-[0.65rem] uppercase tracking-widest text-slate-500 mb-2">
          Claims ({result.claims.length})
        </p>
        <div className="space-y-3">
          {result.claims.map((c, i) => (
            <div
              key={i}
              className="bg-slate-800/40 border border-slate-700 rounded p-3 space-y-2"
            >
              <p className="text-sm text-slate-200 font-medium">&ldquo;{c.claim}&rdquo;</p>
              <div className="flex items-center gap-2 text-xs">
                <span
                  className={cn(
                    "px-1.5 py-0.5 rounded font-bold",
                    c.verdict === "VERIFIED"
                      ? "bg-green-950/60 text-green-400 border border-green-900"
                      : c.verdict === "PARTIAL"
                      ? "bg-yellow-950/60 text-yellow-400 border border-yellow-900"
                      : "bg-red-950/60 text-red-400 border border-red-900"
                  )}
                >
                  {c.verdict}
                </span>
                <span className="text-slate-500">{Math.round(c.confidence * 100)}%</span>
              </div>
              <p className="text-xs text-slate-400">{c.summary}</p>
              {c.receipts.length > 0 && (
                <div className="space-y-1.5 pt-1">
                  {c.receipts.map((r, j) => (
                    <div key={j}>
                      <a
                        href={r.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-[11px] text-slate-400 hover:text-sky-400"
                      >
                        ◆ {r.label}
                      </a>
                      {r.snippet && (
                        <pre className="ml-3 mt-1 px-2 py-1 bg-black/60 border border-slate-800 rounded text-[10px] text-slate-300 whitespace-pre-wrap leading-relaxed overflow-x-auto">
                          {r.snippet.length > 240 ? r.snippet.slice(0, 240) + "…" : r.snippet}
                        </pre>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
