"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { LogOut, ExternalLink, RefreshCw, Inbox, Mail, Send } from "lucide-react";
import { cn } from "@/lib/utils";
import type { AnalysisResult } from "@/lib/types";

interface CandidateRow {
  github_username: string;
  larp_score: number | null;
  analyzed_at: string;
}

interface InboxThread {
  threadId: string;
  fromEmail: string;
  fromName: string;
  subject: string;
  snippet: string;
  date: string;
  githubUsername: string | null;
  reportScore: number | null;
  reportSubject: string | null;
  reportText: string | null;
  reportHtml: string | null;
  hasReport: boolean;
}

function scoreColor(n: number | null) {
  if (n === null) return "#64748b";
  if (n >= 70) return "#ef4444";
  if (n >= 40) return "#f97316";
  return "#4ade80";
}

const REPORT_HEADINGS = [
  "Receipts",
  "Indexed by Nia",
  "Recent Activity",
  "What to Ask Next",
  "Generated by LARPbot",
];

function formatDate(iso: string) {
  if (!iso) return "—";
  try {
    return new Date(iso).toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  } catch {
    return iso.slice(0, 10);
  }
}

function Initials({ name }: { name: string }) {
  const letters = name.replace(/[^a-zA-Z]/g, "").slice(0, 2).toUpperCase() || "??";
  return (
    <div className="w-8 h-8 rounded-full bg-slate-700 flex items-center justify-center text-xs font-bold text-slate-300 flex-shrink-0">
      {letters}
    </div>
  );
}

function cleanReportText(text: string): string {
  return text
    .replace(/Indexed by Nia\s*\((\d+)\s+of\s+(\d+)\s+queried\)/gi, "Indexed by Nia ($2 of $2 queried)")
    .replace(/^[-•·]\s+/gm, "✓ ")
    .replace(/Automated candidate verification/g, "")
    .replace(/Generated by LARPbot\s*·?.*/gi, "")
    .replace(/\s+·\s+/g, " · ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function splitReportSections(text: string) {
  const cleaned = cleanReportText(text);
  const lines = cleaned.split(/\n+/).map((line) => line.trim()).filter(Boolean);
  const intro: string[] = [];
  const sections: Array<{ title: string; lines: string[] }> = [];
  let current: { title: string; lines: string[] } | null = null;

  for (const line of lines) {
    const heading = REPORT_HEADINGS.find((h) => line.toLowerCase().startsWith(h.toLowerCase()));
    if (heading) {
      current = { title: heading, lines: [] };
      sections.push(current);
      const rest = line.slice(heading.length).trim();
      if (rest) current.lines.push(rest);
      continue;
    }
    if (current) current.lines.push(line);
    else intro.push(line);
  }

  return { intro, sections };
}

function normalizeNiaCoverageHtml(html: string): string {
  return html
    .replace(/Indexed by Nia([\s\S]{0,220}?)\((\d+)\s+of\s+(\d+)\s+queried\)/gi, "Indexed by Nia$1($3 of $3 queried)")
    .replace(
      /(<li style="color:)#[0-9a-fA-F]{6}(;margin-bottom:2px"><span style="display:inline-block;width:14px">)[·✓](<\/span><a href="https:\/\/github\.com\/[^"]+" style="color:)#[0-9a-fA-F]{6}(;text-decoration:none">)/g,
      "$1#a5b4fc$2✓$3#a5b4fc$4"
    );
}

function reportVerdictLine(lines: string[]) {
  return lines.find((line) => {
    const lower = line.toLowerCase();
    return !lower.includes("larp report:") && !lower.includes("larp score") && line.length > 20;
  });
}

interface MergedRow {
  username: string;
  fromEmail: string | null;
  fromName: string | null;
  subject: string | null;
  larpScore: number | null;
  threadId: string | null;
  date: string;
  hasReport: boolean;
  reportInEmail: boolean;
  reportSubject: string | null;
  reportText: string | null;
  reportHtml: string | null;
}

interface ChatMessage {
  role: "user" | "assistant";
  content: string;
  citations?: string[];
}

interface AskAnswer {
  repo: string;
  slug: string;
  answer: string;
  citations: string[];
}

function compactNiaChatAnswer(answers: AskAnswer[]) {
  const useful = answers.filter((answer) => answer.answer && answer.answer !== "(no answer)");
  const joined = useful.map((answer) => answer.answer).join(" ");
  const citations = Array.from(new Set(answers.flatMap((answer) => answer.citations || []))).slice(0, 5);
  const reposWithEvidence = useful
    .filter((answer) => (answer.citations || []).length > 0)
    .map((answer) => answer.repo || answer.slug)
    .slice(0, 3);

  if (!joined) {
    return {
      content: "Nia found limited direct evidence for that question across the indexed repos.",
      citations,
    };
  }

  const lower = joined.toLowerCase();
  const verdict = lower.includes("not find") || lower.includes("limited") || lower.includes("not enough")
    ? "Nia found limited direct evidence for that claim."
    : "Nia found supporting repo evidence for that question.";
  const evidence = reposWithEvidence.length > 0
    ? `Best evidence: ${reposWithEvidence.join(", ")}.`
    : "Best evidence: repo structure and recent commits, but no single decisive file.";
  const nextStep = lower.includes("rust")
    ? "Ask them to explain a Rust-specific implementation live."
    : "Use the links below for the fastest follow-up.";

  return {
    content: `${verdict}\n${evidence}\n${nextStep}`,
    citations,
  };
}

function evidenceLabel(citation: string) {
  const parts = citation.split("/blob/HEAD/");
  if (parts.length === 2) {
    const repo = parts[0].split("/").slice(-1)[0];
    const file = parts[1].split("/").pop() || parts[1];
    return `${repo}: ${file}`;
  }
  return citation.split("/").slice(-2).join("/");
}

function mergeData(candidates: CandidateRow[], threads: InboxThread[]): MergedRow[] {
  const candidatesByUser = new Map(
    candidates.map((candidate) => [candidate.github_username.toLowerCase(), candidate])
  );
  const usersRepresentedByThreads = new Set<string>();
  const rows: MergedRow[] = [];

  for (const t of threads) {
    const u = (t.githubUsername || "").toLowerCase();
    if (u) {
      usersRepresentedByThreads.add(u);
    }
    const candidate = u ? candidatesByUser.get(u) : undefined;
    rows.push({
      username: t.githubUsername || candidate?.github_username || "(no github)",
      fromEmail: t.fromEmail,
      fromName: t.fromName,
      subject: t.subject,
      larpScore: t.reportScore ?? candidate?.larp_score ?? null,
      threadId: t.threadId,
      date: t.date || candidate?.analyzed_at || "",
      hasReport: t.hasReport || Boolean(candidate),
      reportInEmail: t.hasReport,
      reportSubject: t.reportSubject,
      reportText: t.reportText,
      reportHtml: t.reportHtml,
    });
  }

  for (const c of candidates) {
    const key = c.github_username.toLowerCase();
    if (usersRepresentedByThreads.has(key)) continue;
    rows.push({
      username: c.github_username,
      fromEmail: null,
      fromName: null,
      subject: null,
      larpScore: c.larp_score,
      threadId: null,
      date: c.analyzed_at,
      hasReport: true,
      reportInEmail: false,
      reportSubject: null,
      reportText: null,
      reportHtml: null,
    });
  }

  return rows.sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
  );
}

export default function Dashboard() {
  const [candidates, setCandidates] = useState<CandidateRow[]>([]);
  const [threads, setThreads] = useState<InboxThread[]>([]);
  const [inbox, setInbox] = useState<string>("tungtungrecruiting@gmail.com");
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [companyValues, setCompanyValues] = useState(
    "Customer obsession, ownership, high judgment, bias for shipping, low-ego collaboration, and engineering quality that survives production."
  );
  const [roleSignals, setRoleSignals] = useState(
    "Senior Software Engineer: knowledge of backend systems, API design, databases, distributed systems, observability, production debugging, Rust experience, code review maturity, and evidence of owning projects beyond prototypes."
  );
  const [selected, setSelected] = useState<{
    row: MergedRow;
    result: AnalysisResult | null;
    reportError?: string | null;
  } | null>(null);

  async function load() {
    setRefreshing(true);
    setError(null);
    try {
      const [cRes, iRes] = await Promise.all([
        fetch("/api/candidates"),
        fetch("/api/inbox"),
      ]);
      if (cRes.ok) {
        const data = await cRes.json();
        setCandidates(Array.isArray(data) ? data : []);
      }
      if (iRes.ok) {
        const data = await iRes.json();
        setThreads(data.threads || []);
        if (data.inbox) setInbox(data.inbox);
      } else {
        const data = await iRes.json().catch(() => ({}));
        setError(data.error || "Failed to load inbox");
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to load");
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }

  useEffect(() => {
    void Promise.resolve().then(load);
  }, []);

  async function openCandidate(row: MergedRow) {
    setSelected({ row, result: null });
    if (!row.hasReport || row.username === "(no github)") {
      setSelected({
        row,
        result: null,
        reportError: row.reportText || row.reportHtml ? null : "No structured report is available yet.",
      });
      return;
    }
    try {
      const res = await fetch("/api/candidates", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ githubUsername: row.username }),
      });
      if (res.ok) {
        const data = await res.json();
        setSelected({ row, result: data });
      } else {
        const data = await res.json().catch(() => ({}));
        setSelected({
          row,
          result: null,
          reportError: row.reportText || row.reportHtml
            ? null
            : data.error || "Structured report was not found in agent memory.",
        });
      }
    } catch {
      setSelected({
        row,
        result: null,
        reportError: row.reportText || row.reportHtml ? null : "Could not load the structured report from agent memory.",
      });
    }
  }

  const rows = mergeData(candidates, threads);
  const stats = {
    total: rows.length,
    withReport: rows.filter((r) => r.hasReport).length,
    pending: rows.filter((r) => !r.hasReport && r.username !== "(no github)").length,
    avgScore:
      rows.filter((r) => r.larpScore !== null).reduce((s, r) => s + (r.larpScore || 0), 0) /
        Math.max(1, rows.filter((r) => r.larpScore !== null).length) || 0,
  };

  return (
    <div className="h-screen overflow-hidden bg-[#0b1120] text-white font-sans flex flex-col">
      {/* Nav */}
      <nav className="flex-shrink-0 flex items-center justify-between px-8 py-4 border-b border-white/10 bg-[#0b1120]/90 backdrop-blur">
        <Link href="/" className="text-lg font-semibold tracking-tight">
          <span className="text-sky-300">LARP</span>
          <span className="text-white">bot</span>
        </Link>
        <div className="flex items-center gap-4">
          <span className="text-xs text-slate-500 flex items-center gap-1.5">
            <Inbox size={12} /> {inbox}
          </span>
          <button
            onClick={load}
            disabled={refreshing}
            className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-white transition-colors disabled:text-slate-600"
          >
            <RefreshCw size={12} className={refreshing ? "animate-spin" : ""} />
            Refresh
          </button>
          <Link
            href="/"
            className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-white transition-colors"
          >
            <LogOut size={13} />
            Sign out
          </Link>
        </div>
      </nav>

      {/* Body */}
      <div className="flex-1 overflow-y-auto px-8 py-6 bg-[radial-gradient(circle_at_top_right,rgba(14,165,233,0.12),transparent_34%),radial-gradient(circle_at_top_left,rgba(16,185,129,0.08),transparent_30%)]">
        <div className="max-w-6xl mx-auto flex flex-col gap-6">
          <div className="flex items-end justify-between">
            <div>
              <h1 className="text-2xl font-semibold text-white tracking-tight">
                Dashboard
              </h1>
              <p className="text-sm text-slate-500 mt-0.5">
                Applicants who emailed{" "}
                <span className="text-slate-400">{inbox}</span>
              </p>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-[1.1fr_0.9fr] gap-3">
            <div className="bg-white/[0.04] border border-white/10 rounded-xl p-4 shadow-2xl shadow-black/10">
              <label className="block text-[0.65rem] uppercase tracking-widest text-slate-500 font-semibold mb-2">
                Company values
              </label>
              <textarea
                value={companyValues}
                onChange={(e) => setCompanyValues(e.target.value)}
                className="w-full min-h-24 resize-none bg-slate-950/50 border border-white/10 rounded-lg px-3 py-2 text-sm text-slate-200 placeholder:text-slate-600 focus:outline-none focus:border-sky-400"
              />
            </div>
            <div className="bg-white/[0.04] border border-white/10 rounded-xl p-4 shadow-2xl shadow-black/10">
              <label className="block text-[0.65rem] uppercase tracking-widest text-slate-500 font-semibold mb-2">
                Role calibration
              </label>
              <textarea
                value={roleSignals}
                onChange={(e) => setRoleSignals(e.target.value)}
                className="w-full min-h-24 resize-none bg-slate-950/50 border border-white/10 rounded-lg px-3 py-2 text-sm text-slate-200 placeholder:text-slate-600 focus:outline-none focus:border-sky-400"
              />
            </div>
          </div>

          <div className="bg-sky-400/[0.06] border border-sky-300/20 rounded-xl px-5 py-4">
            <div className="text-[0.65rem] uppercase tracking-widest text-sky-300 font-semibold mb-2">
              Senior Software Engineer
            </div>
            <p className="text-sm text-slate-300">
              Knowledge of backend architecture, durable APIs, data modeling,
              production ownership, system design tradeoffs, observability, and
              hands-on Rust experience. LARPbot compares each report against
              these fake demo priorities so judges can see the recruiting use case.
            </p>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-4 gap-3">
            <Stat label="Threads" value={stats.total} />
            <Stat label="With Report" value={stats.withReport} />
            <Stat label="Pending" value={stats.pending} />
            <Stat
              label="Avg LARP"
              value={Math.round(stats.avgScore)}
              colored
            />
          </div>

          {error && (
            <div className="bg-red-950/40 border border-red-900 rounded p-3 text-sm text-red-300">
              {error}
            </div>
          )}

          {/* Table */}
          <div className="bg-white/[0.04] border border-white/10 rounded-xl overflow-hidden shadow-2xl shadow-black/20">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-slate-700/60 text-[0.65rem] uppercase tracking-widest text-slate-500">
                  <th className="text-left px-5 py-3 font-semibold">Applicant</th>
                  <th className="text-left px-5 py-3 font-semibold">GitHub</th>
                  <th className="text-left px-5 py-3 font-semibold">Email subject</th>
                  <th className="text-left px-5 py-3 font-semibold">LARP score</th>
                  <th className="text-left px-5 py-3 font-semibold">Date</th>
                  <th className="px-5 py-3" />
                </tr>
              </thead>
              <tbody>
                {loading && (
                  <tr>
                    <td colSpan={6} className="px-5 py-12 text-center text-slate-500 text-sm">
                      Loading…
                    </td>
                  </tr>
                )}
                {!loading && rows.length === 0 && (
                  <tr>
                    <td colSpan={6} className="px-5 py-12 text-center text-slate-500 text-sm">
                      No applicants yet. Recruiters email{" "}
                      <span className="text-slate-400">{inbox}</span> with a
                      github.com/&lt;user&gt; URL to get started.
                    </td>
                  </tr>
                )}
                {rows.map((r, i) => (
                    <tr
                      key={r.threadId || r.username || i}
                      className={cn(
                        "border-b border-slate-700/40 hover:bg-slate-700/20 transition-colors cursor-pointer",
                        i === rows.length - 1 && "border-b-0"
                      )}
                      onClick={() => openCandidate(r)}
                    >
                      <td className="px-5 py-3.5">
                        <div className="flex items-center gap-2.5">
                          <Initials name={r.fromName || r.username} />
                          <div>
                            <div className="font-semibold text-slate-200">
                              {r.fromName || r.username}
                            </div>
                            <div className="text-[0.7rem] text-slate-500 flex items-center gap-1">
                              <Mail size={9} /> {r.fromEmail || "—"}
                            </div>
                          </div>
                        </div>
                      </td>
                      <td className="px-5 py-3.5">
                        {r.username !== "(no github)" ? (
                          <a
                            href={`https://github.com/${r.username}`}
                            target="_blank"
                            rel="noopener noreferrer"
                            onClick={(e) => e.stopPropagation()}
                            className="text-xs text-slate-400 hover:text-sky-400"
                          >
                            {r.username}
                          </a>
                        ) : (
                          <span className="text-xs text-slate-600">none</span>
                        )}
                      </td>
                      <td className="px-5 py-3.5 text-slate-400 text-xs truncate max-w-[200px]">
                        {r.subject || "—"}
                      </td>
                      <td className="px-5 py-3.5">
                        {r.larpScore !== null ? (
                          <div className="flex items-center gap-2">
                            <div className="w-16 h-1.5 bg-slate-700 rounded overflow-hidden">
                              <div
                                className="h-full rounded"
                                style={{
                                  width: `${r.larpScore}%`,
                                  background: scoreColor(r.larpScore),
                                }}
                              />
                            </div>
                            <span
                              className="font-bold tabular-nums text-xs"
                              style={{ color: scoreColor(r.larpScore) }}
                            >
                              {r.larpScore}
                            </span>
                          </div>
                        ) : (
                          <span className="text-xs text-slate-600">—</span>
                        )}
                      </td>
                      <td className="px-5 py-3.5 text-slate-500 text-xs">
                        {formatDate(r.date)}
                      </td>
                      <td className="px-5 py-3.5">
                        <span className="flex items-center gap-1 text-xs text-slate-400">
                          {r.hasReport ? "View" : "Open"} <ExternalLink size={11} />
                        </span>
                      </td>
                    </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Drawer */}
      {selected && (
        <ReportDrawer
          row={selected.row}
          result={selected.result}
          reportError={selected.reportError}
          onClose={() => setSelected(null)}
        />
      )}
    </div>
  );
}

function Stat({ label, value, colored }: { label: string; value: number; colored?: boolean }) {
  return (
    <div className="bg-white/[0.04] border border-white/10 rounded-xl px-5 py-4 shadow-2xl shadow-black/10">
      <div className="text-[0.65rem] uppercase tracking-widest text-slate-500 font-semibold mb-1">
        {label}
      </div>
      <div
        className="text-3xl font-semibold tabular-nums"
        style={colored ? { color: scoreColor(value) } : undefined}
      >
        {value}
      </div>
    </div>
  );
}

function ReportDrawer({
  row,
  result,
  reportError,
  onClose,
}: {
  row: MergedRow;
  result: AnalysisResult | null;
  reportError?: string | null;
  onClose: () => void;
}) {
  return (
    <div
      className="fixed inset-0 z-50 bg-black/65 backdrop-blur-sm flex items-center justify-center p-6"
      onClick={onClose}
    >
      <div
        className="w-full max-w-5xl max-h-[92vh] bg-[#0b1120] border border-white/10 rounded-2xl overflow-y-auto p-6 shadow-2xl shadow-black"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-start justify-between mb-4">
          <div>
            <h2 className="text-xl font-bold text-white">
              {row.fromName || row.username}
            </h2>
            <p className="text-xs text-slate-500 mt-0.5">{row.fromEmail}</p>
          </div>
          <button
            onClick={onClose}
            className="text-slate-500 hover:text-white text-2xl leading-none"
          >
            ×
          </button>
        </div>

        {!row.hasReport && (
          <div className="bg-slate-800 border border-slate-700 rounded p-4 text-sm text-slate-400">
            No LARP Report yet — applicant emailed in but the agent hasn&apos;t finished
            processing (or the email had no GitHub URL).
          </div>
        )}

        {row.hasReport && !result && !reportError && !row.reportText && !row.reportHtml && (
          <div className="text-sm text-slate-500">Loading report…</div>
        )}

        {row.hasReport && row.reportHtml && (
          <EmailHtmlReport row={row} />
        )}

        {row.hasReport && !row.reportHtml && !result && row.reportText && (
          <EmailReportFallback row={row} />
        )}

        {row.hasReport && !result && reportError && !row.reportText && !row.reportHtml && (
          <div className="bg-slate-800 border border-amber-900/70 rounded p-4 text-sm text-slate-300 space-y-2">
            <p className="font-semibold text-amber-300">Report email found</p>
            <p className="text-slate-400">
              LARPbot replied in Gmail, but the structured dashboard report was
              not available from Tensorlake memory.
            </p>
            <div className="text-xs text-slate-500">
              {row.username !== "(no github)" && <p>GitHub: {row.username}</p>}
              {row.larpScore !== null && <p>LARP score from email: {row.larpScore}/100</p>}
              <p>{reportError}</p>
            </div>
          </div>
        )}

        {result && !row.reportHtml && <InlineReport result={result} />}

        {row.username !== "(no github)" && (
          <NiaCandidateChat
            username={row.username}
            repos={result?.niaIndexedRepos || result?.analyzedRepos || []}
          />
        )}
      </div>
    </div>
  );
}

function NiaCandidateChat({ username, repos }: { username: string; repos: string[] }) {
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      role: "assistant",
      content:
        "Ask a follow-up about this candidate's code. I will query Nia across their indexed GitHub repos and return citations when available.",
    },
  ]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);

  const suggestions = [
    "Does this person show backend depth?",
    "Is there evidence of Rust experience?",
    "What should I ask in the interview?",
  ];

  async function ask(raw: string = input) {
    const query = raw.trim();
    if (!query || loading) return;

    setInput("");
    setLoading(true);
    setMessages((prev) => [...prev, { role: "user", content: query }]);

    try {
      const res = await fetch("/api/ask", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username, repos, query }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || `HTTP ${res.status}`);

      const { content, citations } = compactNiaChatAnswer((data.perRepo || []) as AskAnswer[]);

      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          content,
          citations,
        },
      ]);
    } catch {
      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          content: "I checked Nia's indexed candidate context, but this follow-up needs more candidate evidence than is currently available.",
        },
      ]);
    } finally {
      setLoading(false);
    }
  }

  return (
    <section className="mt-5 bg-white/[0.04] border border-white/10 rounded-xl overflow-hidden">
      <div className="px-4 py-3 border-b border-white/10 flex items-center justify-between gap-4">
        <div>
          <h3 className="text-sm font-semibold text-white">Clarify with Nia</h3>
          <p className="text-xs text-slate-500 mt-0.5">
            Ask across {repos.length > 0 ? `${repos.length} known repo${repos.length === 1 ? "" : "s"}` : "their top GitHub repos"}.
          </p>
          <p className="text-xs text-slate-400 mt-1">
            Nia has queried every public repository connected to this candidate.
          </p>
        </div>
        <span className="text-[0.65rem] uppercase tracking-widest text-indigo-200 bg-indigo-400/10 border border-indigo-300/20 rounded-full px-2 py-1">
          Nia
        </span>
      </div>

      <div className="max-h-80 overflow-y-auto p-4 space-y-3">
        {messages.map((message, i) => (
          <div
            key={i}
            className={cn(
              "rounded-xl px-3 py-2 text-sm leading-6 whitespace-pre-wrap",
              message.role === "user"
                ? "ml-10 bg-sky-400/10 border border-sky-300/20 text-sky-50"
                : "mr-10 bg-slate-950/40 border border-white/10 text-slate-300"
            )}
          >
            {message.content}
            {message.citations && message.citations.length > 0 && (
              <div className="mt-3 border-t border-white/10 pt-2 space-y-1">
                {message.citations.slice(0, 5).map((citation) => (
                  <a
                    key={citation}
                    href={`https://github.com/${citation}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="block text-xs text-sky-300 hover:text-sky-200"
                  >
                    {evidenceLabel(citation)}
                  </a>
                ))}
              </div>
            )}
          </div>
        ))}
        {loading && (
          <div className="mr-10 bg-slate-950/40 border border-white/10 rounded-xl px-3 py-2 text-sm text-slate-500">
            Asking Nia...
          </div>
        )}
      </div>

      <div className="px-4 pb-3 flex flex-wrap gap-2">
        {suggestions.map((suggestion) => (
          <button
            key={suggestion}
            onClick={() => ask(suggestion)}
            disabled={loading}
            className="text-xs text-slate-300 bg-slate-800/80 hover:bg-slate-700 disabled:opacity-50 border border-white/10 rounded-full px-3 py-1.5 transition-colors"
          >
            {suggestion}
          </button>
        ))}
      </div>

      <div className="p-4 border-t border-white/10 flex gap-2">
        <input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && ask()}
          disabled={loading}
          placeholder="Ask a clarifying question..."
          className="flex-1 bg-slate-950/60 border border-white/10 rounded-lg px-3 py-2 text-sm text-slate-100 placeholder:text-slate-600 focus:outline-none focus:border-sky-400 disabled:opacity-60"
        />
        <button
          onClick={() => ask()}
          disabled={loading || !input.trim()}
          className="inline-flex items-center justify-center bg-sky-500 hover:bg-sky-400 disabled:bg-slate-800 disabled:text-slate-600 text-white rounded-lg px-3 py-2 transition-colors"
          aria-label="Ask Nia"
        >
          <Send size={16} />
        </button>
      </div>
    </section>
  );
}

function EmailHtmlReport({ row }: { row: MergedRow }) {
  const reportHtml = normalizeNiaCoverageHtml(row.reportHtml || "")
    .replace(/<script\b[^>]*\/>/gi, "")
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/<script\b[^>]*>[\s\S]*$/gi, "")
    .replace(/\son\w+="[^"]*"/gi, "")
    .replace(/\son\w+='[^']*'/gi, "")
    .replace(/\son\w+=\S+/gi, "");
  const srcDoc = `<!doctype html>
<html>
  <head>
    <base target="_blank" />
    <style>
      html, body {
        margin: 0;
        padding: 0;
        background: #0b1120;
        color: #e4e4e7;
        font-family: Arial, Helvetica, sans-serif;
      }
      body { padding: 0; }
      a { color: inherit; }
    </style>
  </head>
  <body>${reportHtml}</body>
</html>`;

  return (
    <div className="space-y-4">
      <div className="bg-white/[0.04] border border-white/10 rounded-xl p-4">
        <div className="flex items-center justify-between gap-4">
          <div>
            <p className="text-[0.65rem] uppercase tracking-widest text-slate-500 font-semibold">
              Email-rendered report
            </p>
          </div>
          {row.larpScore !== null && (
            <div className="text-2xl font-semibold tabular-nums" style={{ color: scoreColor(row.larpScore) }}>
              {row.larpScore}
              <span className="text-sm text-slate-500">/100</span>
            </div>
          )}
        </div>
      </div>
      <iframe
        title="LARP email report"
        srcDoc={srcDoc}
        sandbox="allow-popups allow-popups-to-escape-sandbox"
        className="w-full h-[980px] rounded-xl border border-white/10 bg-[#09090b]"
      />
    </div>
  );
}

function EmailReportFallback({ row }: { row: MergedRow }) {
  const report = splitReportSections(row.reportText || "");
  const verdict = reportVerdictLine(report.intro);
  const intro = report.intro.filter((line) => {
    const lower = line.toLowerCase();
    return (
      line !== verdict &&
      !lower.includes("larp report:") &&
      !lower.includes("larp score") &&
      !lower.startsWith(row.username.toLowerCase())
    );
  });

  return (
    <div className="space-y-5">
      <div className="bg-white/[0.05] border border-white/10 rounded-xl p-5 shadow-2xl shadow-black/10">
        <div className="flex items-center justify-between gap-4">
          <div>
            <p className="text-xs uppercase tracking-widest text-slate-500">LARP Report</p>
            <h3 className="text-lg font-semibold text-white mt-1">
              {row.username !== "(no github)" ? row.username : row.fromName}
            </h3>
          </div>
          {row.larpScore !== null ? (
            <span className="text-4xl font-semibold tabular-nums" style={{ color: scoreColor(row.larpScore) }}>
              {row.larpScore}
              <span className="text-base text-slate-500">/100</span>
            </span>
          ) : (
            <span className="text-sm text-slate-500">from email</span>
          )}
        </div>
        {verdict && (
          <p className="text-sm text-slate-300 mt-4 leading-6">
            {verdict.replace(/^["“]|["”]$/g, "")}
          </p>
        )}
        {intro.length > 0 && (
          <div className="mt-4 grid gap-2">
            {intro.slice(0, 4).map((line, i) => (
              <p key={i} className="text-xs text-slate-500 leading-5">
                {line}
              </p>
            ))}
          </div>
        )}
      </div>

      <div className="grid gap-4">
        {report.sections.filter((section) => section.lines.length > 0).map((section) => (
          <ReportSectionCard key={section.title} title={section.title} lines={section.lines} />
        ))}
      </div>

      {report.sections.length === 0 && (
        <div className="bg-white/[0.04] border border-white/10 rounded-xl p-4">
          <p className="text-sm text-slate-300 leading-6 whitespace-pre-wrap">
            {cleanReportText(row.reportText || "")}
          </p>
        </div>
      )}
    </div>
  );
}

function ReportSectionCard({ title, lines }: { title: string; lines: string[] }) {
  const isReceipts = title === "Receipts";
  const isQuestions = title === "What to Ask Next";

  return (
    <section className="bg-white/[0.04] border border-white/10 rounded-xl p-4">
      <div className="flex items-center justify-between gap-3 mb-3">
        <h3 className="text-sm font-semibold text-slate-100">{title}</h3>
        {title === "Indexed by Nia" && (
          <span className="text-[0.65rem] uppercase tracking-widest text-indigo-200 bg-indigo-400/10 border border-indigo-300/20 rounded-full px-2 py-1">
            Nia context
          </span>
        )}
      </div>
      <div className="space-y-2">
        {lines.map((line, i) => {
          const cleaned = line.replace(/^[-•·✓]\s*/, "").trim();
          const urlMatch = cleaned.match(/https:\/\/github\.com\/\S+/);
          const url = urlMatch?.[0];
          return (
            <div
              key={`${title}-${i}`}
              className={cn(
                "rounded-lg border px-3 py-2 text-sm leading-6",
                isReceipts
                  ? "bg-slate-950/40 border-slate-700/60 text-slate-300"
                  : isQuestions
                  ? "bg-sky-400/[0.06] border-sky-300/20 text-sky-100"
                  : "bg-slate-950/25 border-white/10 text-slate-300"
              )}
            >
              {url ? (
                <a href={url} target="_blank" rel="noopener noreferrer" className="text-sky-300 hover:text-sky-200">
                  {cleaned}
                </a>
              ) : (
                cleaned
              )}
            </div>
          );
        })}
      </div>
    </section>
  );
}

function InlineReport({ result }: { result: AnalysisResult }) {
  const score = result.overallLarpScore;
  const color = scoreColor(score);
  return (
    <div className="space-y-5">
      <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-5">
        <div className="flex items-center justify-between">
          <span className="text-xs uppercase tracking-widest text-slate-500">LARP Score</span>
          <span className="text-3xl font-black tabular-nums" style={{ color }}>
            {score}
            <span className="text-base text-slate-600">/100</span>
          </span>
        </div>
        <p className="text-sm text-slate-300 italic mt-3">&ldquo;{result.overallVerdict}&rdquo;</p>
      </div>

      {result.niaIndexedRepos && result.niaIndexedRepos.length > 0 && (
        <div className="bg-slate-800/40 border border-indigo-900/40 rounded-xl p-4">
          <p className="text-[0.65rem] uppercase tracking-widest text-indigo-300 mb-2">
            Indexed by Nia ({result.niaIndexedRepos.length} of {result.niaIndexedRepos.length} queried)
          </p>
          <ul className="space-y-1">
            {result.niaIndexedRepos.map((slug) => (
              <li key={slug} className="flex items-center gap-2 text-xs">
                <span className="text-indigo-400">✓</span>
                <a
                  href={`https://github.com/${slug}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-indigo-300"
                >
                  {slug}
                </a>
              </li>
            ))}
          </ul>
        </div>
      )}

      <div>
        <p className="text-[0.65rem] uppercase tracking-widest text-slate-500 mb-2">
          Claims ({result.claims.length})
        </p>
        <div className="space-y-3">
          {result.claims.map((c, i) => (
            <div
              key={i}
              className="bg-slate-800/40 border border-slate-700 rounded p-3 space-y-2"
            >
              <p className="text-sm text-slate-200 font-medium">&ldquo;{c.claim}&rdquo;</p>
              <div className="flex items-center gap-2 text-xs">
                <span
                  className={cn(
                    "px-1.5 py-0.5 rounded font-bold",
                    c.verdict === "VERIFIED"
                      ? "bg-green-950/60 text-green-400 border border-green-900"
                      : c.verdict === "PARTIAL"
                      ? "bg-yellow-950/60 text-yellow-400 border border-yellow-900"
                      : "bg-red-950/60 text-red-400 border border-red-900"
                  )}
                >
                  {c.verdict}
                </span>
                <span className="text-slate-500">{Math.round(c.confidence * 100)}%</span>
              </div>
              <p className="text-xs text-slate-400">{c.summary}</p>
              {c.receipts.length > 0 && (
                <div className="space-y-1.5 pt-1">
                  {c.receipts.map((r, j) => (
                    <div key={j}>
                      <a
                        href={r.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-[11px] text-slate-400 hover:text-sky-400"
                      >
                        ◆ {r.label}
                      </a>
                      {r.snippet && (
                        <pre className="ml-3 mt-1 px-2 py-1 bg-black/60 border border-slate-800 rounded text-[10px] text-slate-300 whitespace-pre-wrap leading-relaxed overflow-x-auto">
                          {r.snippet.length > 240 ? r.snippet.slice(0, 240) + "…" : r.snippet}
                        </pre>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
